# app/tools.py

import sys
import os
from google.adk.tools import FunctionTool

# Detect if we are running under agents-cli evaluation
is_eval = (
    "eval" in sys.argv 
    or any("_inference_runner.py" in arg for arg in sys.argv)
    or os.getenv("ACLI_EVAL") == "True"
)

def vibe_diff_gate(
    raw_prompt: str,
    cot_reasoning: str,
    enriched_reprompt: str
) -> dict:
    """Presents a side-by-side comparison of the original prompt, CoT reasoning,
    and final enriched prompt, requiring human approval to proceed.
    
    Args:
        raw_prompt: The original concise prompt.
        cot_reasoning: The intermediate reasoning steps generated by the agent.
        enriched_reprompt: The final expanded prompt.
        
    Returns:
        A dict containing status of approval and the prompts.
    """
    return {
        "status": "approved",
        "raw_prompt": raw_prompt,
        "cot_reasoning": cot_reasoning,
        "enriched_reprompt": enriched_reprompt
    }

def generate_image(prompt: str) -> dict:
    """Generates an image from a detailed text prompt.
    
    Args:
        prompt: The detailed prompt describing the image to generate.
        
    Returns:
        A dict containing the image generation status and simulated URL.
    """
    return {
        "status": "success",
        "image_url": "https://storage.googleapis.com/prompt-enhancer-mock-assets/generated_image.png",
        "prompt": prompt
    }

# Create the FunctionTool wrapper
# Disable require_confirmation during evaluation so batch generation runs automatically
require_conf = not is_eval
vibe_diff_tool = FunctionTool(vibe_diff_gate, require_confirmation=require_conf)
