# app/tools.py

import sys
import os
from google.adk.tools import FunctionTool

# Detect if we are running under agents-cli evaluation
is_eval = (
    "eval" in sys.argv 
    or any("_inference_runner.py" in arg for arg in sys.argv)
    or os.getenv("ACLI_EVAL") == "True"
)

def vibe_diff_gate(
    raw_prompt: str,
    cot_reasoning: str,
    enriched_reprompt: str
) -> dict:
    """Presents a side-by-side comparison of the original prompt, CoT reasoning,
    and final enriched prompt, requiring human approval to proceed.
    
    Args:
        raw_prompt: The original concise prompt.
        cot_reasoning: The intermediate reasoning steps generated by the agent.
        enriched_reprompt: The final expanded prompt.
        
    Returns:
        A dict containing status of approval and the prompts.
    """
    return {
        "status": "approved",
        "raw_prompt": raw_prompt,
        "cot_reasoning": cot_reasoning,
        "enriched_reprompt": enriched_reprompt
    }

import base64
from google import genai

def generate_image(prompt: str) -> dict:
    """Generates an image from a detailed text prompt using Imagen 3.
    
    Args:
        prompt: The detailed prompt describing the image to generate.
        
    Returns:
        A dict containing the image generation status and data URI.
    """
    try:
        # Use Vertex AI natively (Cloud Run ADC will automatically authenticate)
        client = genai.Client(vertexai=True, location=os.getenv("GOOGLE_CLOUD_LOCATION", "us-east1"))
        result = client.models.generate_images(
            model='imagen-3.0-generate-001',
            prompt=prompt,
            config=dict(
                number_of_images=1,
                output_mime_type="image/jpeg",
                aspect_ratio="1:1"
            )
        )
        if not result.generated_images:
            return {
                "status": "error",
                "message": "No images generated by Imagen",
                "prompt": prompt
            }
        
        image_bytes = result.generated_images[0].image.image_bytes
        b64_str = base64.b64encode(image_bytes).decode('utf-8')
        data_uri = f"data:image/jpeg;base64,{b64_str}"
        
        return {
            "status": "success",
            "image_url": data_uri,
            "prompt": prompt
        }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e),
            "prompt": prompt
        }

# Create the FunctionTool wrapper
# Disable require_confirmation during evaluation so batch generation runs automatically
require_conf = not is_eval
vibe_diff_tool = FunctionTool(vibe_diff_gate, require_confirmation=require_conf)
